version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    allow:
      - dependency-type: direct
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
