// WARNING! This file is generated by a tool.
// It exists only to allow PO editors to get translation keys from source code.
_" + categoryId }}")
_' + category.categoryId">{{ ')
_' + category.categoryId" type="checkbox" v-model="category.checked" :id="category.categoryId" :name="')
_" + cat + ")
_" + tag + ")
_" + type + ")